apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediqueue.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mediqueue.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "mediqueue.workerSelectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "mediqueue.workerSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "mediqueue.workerServiceAccountName" . }}
      automountServiceAccountToken: false
      priorityClassName: mediqueue-worker-normal
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: mediqueue-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediqueue-db-credentials
                  key: app-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediqueue-redis-credentials
                  key: redis-password
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "pgrep -f worker"]
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: scratch
              mountPath: /var/worker/scratch
      volumes:
        - name: tmp
          emptyDir: {}
        - name: scratch
          persistentVolumeClaim:
            claimName: {{ include "mediqueue.fullname" . }}-worker-scratch
