apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediqueue.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mediqueue.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "mediqueue.apiSelectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "mediqueue.apiSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "mediqueue.serviceAccountName" . }}
      automountServiceAccountToken: false
      priorityClassName: mediqueue-api-high
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mediqueue-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediqueue-db-credentials
                  key: app-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediqueue-redis-credentials
                  key: redis-password
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
